# Используем официальный образ Node.js
FROM node:20-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Открываем порт для Vite dev server (по умолчанию 5173)
EXPOSE 5173

# Запускаем dev server
CMD ["npm", "run", "dev"]
