name: Build and Test Docker

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --target tests -t bablobudget-tests './Lab Work №5/src/API'

      - name: Run tests
        run: docker run --rm bablobudget-tests
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bablobudget-api './Lab Work №5/src/API'

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bablobudget-api

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bablobudget-client './Lab Work №5/src/Client'

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bablobudget-client
